- name: Ensure hardware virt is supported
  shell: test "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" -ge 1

- name: Installs packages
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=300
  with_items:
    - bridge-utils
    - libvirt-bin
    - qemu-kvm

- name: Add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes
  register: result
  ignore_errors: yes

- name: Add user to libvirtd group
  user:
    name: "{{ user }}"
    groups: libvirtd
    append: yes
  when: result|failed

- name: Gets docker machine version
  uri: url=https://api.github.com/repos/docker/machine/releases/latest
       return_content=yes
  register: response

- name: Sets docker machine version fact
  set_fact:
      docker_machine_version: "{{ (response.content | from_json).name }}"

- name: Gets docker machine checksum
  uri: url=https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/sha256sum.txt
       return_content=yes
  register: response

- name: Sets docker machine checksum fact
  set_fact:
      docker_machine_checksum: "sha256:{{ response.content | regex_replace('(?s).*? ([^ ]*) *docker-machine-Linux-x86_64.*', '\\1') }}"

- name: Installs docker-machine
  get_url: url=https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-Linux-x86_64
           dest=/usr/local/bin/docker-machine
           checksum={{ docker_machine_checksum }}
           owner=root
           group=root
           mode=0755

- name: Gets docker machine kvm version
  uri: url=https://api.github.com/repos/dhiltgen/docker-machine-kvm/releases/latest
       return_content=yes
  register: response

- name: Sets docker machine kvm version fact
  set_fact:
      docker_machine_kvm_version: "{{ (response.content | from_json).name }}"

- name: Sets docker machine driver kvm checksum fact
  set_fact:
      docker_machine_kvm_checksum: "md5:{{ response.content | regex_replace('(?s).*?docker-machine-driver-kvm.*?ubuntu16.04 - md5: ([^ ]*).*', '\\1') }}"

- name: Installs docker-machine-driver-kvm
  get_url: url=https://github.com/dhiltgen/docker-machine-kvm/releases/download/{{ docker_machine_kvm_version }}/docker-machine-driver-kvm-ubuntu16.04
           dest=/usr/local/bin/docker-machine-driver-kvm
           checksum={{ docker_machine_kvm_checksum }}
           owner=root
           group=root
           mode=0755

- name: Gets kubectl version response
  uri: url=https://storage.googleapis.com/kubernetes-release/release/stable.txt
       return_content=yes
  register: response

- name: Sets kubectl version fact
  set_fact:
      kubectl_version: "{{ response.content | replace('\n', '') }}"

- name: Gets kubectl checksum
  uri: url="https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl.sha1"
       return_content=yes
  register: response

- name: Sets kubectl checksum fact
  set_fact:
      kubectl_checksum: "sha1:{{ response.content | replace('\n', '') }}"

- name: Installs kubectl
  get_url: url="https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
           dest=/usr/local/bin/kubectl
           checksum={{ kubectl_checksum }}
           owner=root
           group=root
           mode=0755

- name: Gets minikube checksum
  uri: url=https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64.sha256
       return_content=yes
  register: response

- name: Sets minikube checksum fact
  set_fact:
      minikube_checksum: "sha256:{{ response.content | replace('\n', '') }}"

- name: Override minikube checksum fact - https://github.com/kubernetes/minikube/issues/1632
  set_fact:
      minikube_checksum: "sha256:f7447a37332879b934bf7fcae97327367a5b92d33d12ea24301c212892efe326"

- name: Installs minikube
  get_url: url=https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
           dest=/usr/local/bin/minikube
           checksum={{ minikube_checksum }}
           owner=root
           group=root
           mode=0755

- name: Set KVM as minkube hypervisor
  command: minikube config set vm-driver kvm
