- name: Ensure hardware virt is supported
  shell: test "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" -ge 1

- name: Installs packages
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=300
  with_items:
    - bridge-utils
    - libvirt-bin
    - qemu-kvm

- name: Add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes
  register: result
  ignore_errors: yes

- name: Add user to libvirtd group
  user:
    name: "{{ user }}"
    groups: libvirtd
    append: yes
  when: result|failed

# TODO(jesse): Add checksum retrieval and verification for docker-machine
# TODO(jesse): Download latest
- name: Installs docker-machine
  get_url: url=https://github.com/docker/machine/releases/download/v0.11.0/docker-machine-Linux-x86_64
           dest=/usr/local/bin/docker-machine
           owner=root
           group=root
           mode=0755

# TODO(jesse): Add checksum retrieval and verification for docker-machine-driver-kvm
# TODO(jesse): Download latest
- name: Installs docker-machine-driver-kvm
  get_url: url=https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04
           dest=/usr/local/bin/docker-machine-driver-kvm
           owner=root
           group=root
           mode=0755

- name: Gets kubectl version response
  uri: url=https://storage.googleapis.com/kubernetes-release/release/stable.txt
       return_content=yes
  register: response

- name: Sets kubectl version fact
  set_fact:
      kubectl_version: "{{ response.content | replace('\n', '') }}"

- name: Gets kubectl checksum
  uri: url="https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl.sha1"
       return_content=yes
  register: response

- name: Sets kubectl checksum fact
  set_fact:
      kubectl_checksum: "sha1:{{ response.content | replace('\n', '') }}"

- name: Installs kubectl
  get_url: url="https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
           dest=/usr/local/bin/kubectl
           checksum={{ kubectl_checksum }}
           owner=root
           group=root
           mode=0755

- name: Gets minikube checksum
  uri: url=https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64.sha256
       return_content=yes
  register: response

- name: Sets minikube checksum fact
  set_fact:
      minikube_checksum: "sha256:{{ response.content | replace('\n', '') }}"

- name: Override minikube checksum fact - https://github.com/kubernetes/minikube/issues/1632
  set_fact:
      minikube_checksum: "sha256:f7447a37332879b934bf7fcae97327367a5b92d33d12ea24301c212892efe326"

- name: Installs minikube
  get_url: url=https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
           dest=/usr/local/bin/minikube
           checksum={{ minikube_checksum }}
           owner=root
           group=root
           mode=0755

- name: Set KVM as minkube hypervisor
  command: minikube config set vm-driver kvm
